### ISSUE TITLE
Display incorrect flag attempt as an error text next to the field, not as it’s own page

### ISSUE THREAD

**Issue by felixbade** [felixbade/ctf-platform#6]

**Comment by joeljuhela** [comment]
Message flashing was implemented with user authentication, maybe that would be a good fit for this? 
<https://flask.palletsprojects.com/en/2.1.x/patterns/flashing/>

**Comment by felixbade** [comment]
I think the error should be next to the input field, because that would follow the ”direct manipulation” design principle
